### ISSUE TITLE
Failed to compile with gcc v8.5

### ISSUE THREAD

**Issue by xuxocast** [ablab/tandemQUAST#12]
When tried to compile with gcc 8.5 it droped the error:

~/VerityMap/veritymap/src/projects/veritymap/config/config.cpp:17:18: error: 'class std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >' has no member named 'contains'

When update gcc to v14.2.1 drops the error:

~/VerityMap/veritymap/src/projects/veritymap/kmer_index/target_indexer.hpp:92:64: error: ‘optional’ in namespace ‘std’ does not name a template type

Could you please provide compiling instructions? compiler version or update flags to improve compatibility.

Regards.
